apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.serviceClusterIP.name }}
spec:
    type: {{ .Values.serviceClusterIP.type }}
    ports:
        - port: {{ .Values.serviceClusterIP.externalPort }}
          targetPort: {{ .Values.serviceClusterIP.internalPort }}
    selector:
        app: {{ .Values.labelMaster }}
