apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes:
    - {{ .Values.pv.mode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}



