apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: {{ .Values.pv.type }}
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - {{ .Values.pv.mode }}
  hostPath:
    path: "{{ .Values.pv.path }}"